Textures and stuff
TheChernoCommunity/GameProject-1 pull request #23
Opened 2020-11-03 18:37 UTC by Vironacorus

Added GLTexture.h/.cpp.

2020-11-03 23:03 UTC, sfulham commented
You need to update this PR as the GLTexture files aren't actually there

2020-11-03 23:06 UTC, sfulham requested changes
You need to update this PR as the GLTexture files aren't actually there

2020-11-05 10:38 UTC, sfulham approved these changes

2020-11-07 17:08 UTC, Gaztin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Texture Support](https://trello.com/c/RSkLm2li/27-texture-support)

2020-11-24 18:20 UTC, closed without merging