Added GLM(i think?) and a free cam class
TheChernoCommunity/GameProject-1 pull request #25
Opened 2020-11-04 16:23 UTC by matty2048

as above, need to add glm to premake but i havent a clue how to do that

2020-11-07 17:06 UTC, Gaztin requested changes

2020-11-07 17:06 UTC, Gaztin commented on build/vs2019/FreeCam.h
> +		}
Avoid implementations in header files, unless they are one-liners and single-instruction 😊

2020-11-07 17:06 UTC, Gaztin commented on build/vs2019/FreeCam.h
> +		glm::mat4 ViewMatrix; //the view matrix of the camera
Kinda hard to read. Would appreciate it if the functions were bundled together, and the variables bundled together. Also, please follow the naming convention 👍

2020-11-07 17:06 UTC, Gaztin commented on src/Game/Game.cpp
> +
How did this get here?

2020-11-07 17:07 UTC, Gaztin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Camera Controller](https://trello.com/c/eZDAvXka/24-camera-controller)

2020-11-07 17:51 UTC, matty2048 commented on src/Game/Game.cpp
> +
i have no idea....

2020-11-12 17:20 UTC, Gaztin approved these changes

2020-11-14 11:57 UTC, merged